import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MatUrl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className={styles.home__main}>
          <p>The privacy-friendly URL Shortener</p>
        </div>
        <div className={styles.home__sub}>
          <p>
            It's free to use and you can use it to shorten any URL you want.
          </p>
        </div>
        <div className={styles.home__input}>
          <input type="text" placeholder="Enter a URL to shorten" />
          <button>icon</button>
        </div>
      </div>
    </div>
  );
}
